version: '3.8'

services:

  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}

  evolution-api:
    image: atendai/evolution-api
    container_name: evolution-api
    ports:
      - "5600:8080"
    environment:
      - AUTHENTICATION_API_KEY=${EVOLUTION_API_KEY}
    volumes:
      - evolution_store:/evolution/store
      - evolution_instances:/evolution/instances
    restart: unless-stopped

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    environment:
      - NGROK_AUTHTOKEN=${NGROK_TOKEN}
    command: http evolution-api:8080
    ports:
      - "4040:4040"
    depends_on:
      - evolution-api
    restart: unless-stopped

volumes:
  n8n_data:
  evolution_store:
  evolution_instances:
